name: sar2
base: core18 # the base snap is the execution environment for this snap
version: '2.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A rescue helicopter simulator for Linux
description: |
  Search and Rescue II is a rescue helicopter simulator for Linux. It features
  several missions where the player pilots a helicopter in order to rescue
  people in distress in several world locations while flying different
  helicopter models.

  Search and Rescue II supports input from multiple joysticks (needs "snap
  connect sar2:joystick"), including rudder pedals.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  sar2:
    command: "$SNAP/usr/bin/sar2"
    command-chain: ["snap/command-chain/alsa-launch"]
    environment:
      SAR2_DATA: "$SNAP/usr/share/sar2"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
    plugs:
      - x11
      - opengl
      - audio-playback
      - joystick
      - desktop
      - desktop-legacy

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/pixmaps:
    bind: $SNAP/usr/share/pixmaps

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
  sar2:
    after: [alsa-mixin]
    plugin: scons
    scons-options: ["--prefix=/root/parts/sar2/install"]
    source: .
    build-packages:
      - mesa-common-dev
      - libalut-dev
      - libopenal-dev
      - libvorbis-dev
      - libsdl2-dev
      - libice-dev
      - libsm-dev
      - libx11-dev
      - libxext-dev
      - libxmu-dev
      - libxpm-dev
    stage-packages:
      - libalut0
      - libasyncns0
      - libflac8
      - libgl1
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - libogg0
      - libopenal1
      - libpulse0
      - libsdl2-2.0-0
      - libsndfile1
      - libsndio6.1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxpm4
      - libxrandr2
      - libxrender1
      - libxss1
      - libxxf86vm1
